parquet_data_path = 'patient_sequence'
feather_data_path = 'patient_sequence.feather'
tokenizer_path = 'tokenizer.pickle'
time_attention_model_path = 'time_attention_model_path.h5'
bert_model_path = 'bert_model_path.h5'
temporal_bert_model_path = 'temporal_bert_model_path.h5'
