PERSON = 'person'
VISIT_OCCURRENCE = 'visit_occurrence'
CONDITION_OCCURRENCE = 'condition_occurrence'
PROCEDURE_OCCURRENCE = 'procedure_occurrence'
DRUG_EXPOSURE = 'drug_exposure'
DEVICE_EXPOSURE = 'device_exposure'
OBSERVATION = 'observation'
MEASUREMENT = 'measurement'
OBSERVATION_PERIOD = 'observation_period'
CDM_TABLES = [PERSON, VISIT_OCCURRENCE, CONDITION_OCCURRENCE, PROCEDURE_OCCURRENCE, DRUG_EXPOSURE,
              DEVICE_EXPOSURE, OBSERVATION, MEASUREMENT, OBSERVATION_PERIOD]
REQUIRED_MEASUREMENT = 'required_measurement'
UNKNOWN_CONCEPT = '[UNKNOWN]'
